### ISSUE TITLE
Time zone issues with events cards

### ISSUE THREAD

**Issue by hadro** [IIIF/website#520]
[Featured event card tabs](https://beta.iiif.io/news-and-events/#featured-events) have the date and time set to GMT (via the Z designator), but the cards are simply displaying that fixed time without any time zone label, so they'll be incorrect in every time zone _except_ GMT: 

![image](https://user-images.githubusercontent.com/81478/139880808-43f66e11-5f09-4319-8b35-5a8ab3de7018.png)

The data for the first event:
```yml
- label: IIIF Workshop at Learn@DLF (coinciding with DLF Forum and NDSA's Digital Preservation)
  time:
    start: 2021-11-09T16:00:00Z
    end: 2021-11-09T18:00:00Z
  location:
    label: Midspace
    link: https://midspace.forum2021.diglib.org/conference/clir-events
  links:
    - label: Event Details
      link: https://forum2021.diglib.org/
```
